### ISSUE TITLE
本地npm run dev报错

### ISSUE THREAD

**Issue by 17692011070** [Laomai-codefee/pdfjs-annotation-extension#12]
node 版本 V16.20.1
clone下来后，在本地运行 npm run dev 后出现了Warning报错；

**Comment by 17692011070** [comment]
![image](https://github.com/user-attachments/assets/0c0f7580-c905-4fe0-81b8-34133820e56b)

**Comment by zbzzz** [comment]
node版本18.04，我也报了相同的错误，请问您是怎么解决的
![image](https://github.com/user-attachments/assets/774d7947-19c4-4c73-9f0e-7d2f798091ed)

**Comment by Sioncovy** [comment]
> node版本18.04，我也报了相同的错误，请问您是怎么解决的 ![image](https://private-user-images.githubusercontent.com/51048073/381021941-774d7947-19c4-4c73-9f0e-7d2f798091ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjAzMDUsIm5iZiI6MTczMDk2MDAwNSwicGF0aCI6Ii81MTA0ODA3My8zODEwMjE5NDEtNzc0ZDc5NDctMTljNC00YzczLTlmMGUtN2QyZjc5ODA5MWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA2MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjN2U1OWU0MTE0NDE3NGE1ODJkNDczZWI0NDEwMGI4M2VlNGJlNjRmYWI1ZThiNjE4MDI1OGFlNDE1MzQ3NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qRL11ATkHdWpIb_WaUWEIxC8b8QF9Z2gseKjvGH9C2M)

我也这样报错了，请问你后续解决了吗？

**Comment by Laomai-codefee** [comment]
不影响的，已经编译成功了，需要到 pdfjs dist 目录去启动静态服务才行
