### ISSUE TITLE
konvaClientRect 的 x y  值和距离页面尺寸不一致

### ISSUE THREAD

**Issue by 948764321** [Laomai-codefee/pdfjs-annotation-extension#15]
批注的 konvaClientRect 值 发到后端进行存储，这个值是不对吗？明细小于实际值

**Comment by 948764321** [comment]
还是说需要转换坐标系呢？我看 v1.0 版本也是用的这个坐标通过 pdfjs 存储的，和页面尺寸坐标不一样吗？

**Comment by 948764321** [comment]
假设一个批注在 PDF 文档中的位置坐标是(x,y)（单位为点），转换为像素的公式如下：
x_px=(x * scale * DPI)/72
y_px=(y * scale * DPI)/72
例如，如果一个批注的 x 坐标在 PDF 文档中是 10 点，当前缩放比例scale = 1.5，设备像素密度DPI = 96，那么转换为像素后的 x 坐标为：
x_px=(10 * 1.5 * 96)/72 = 20px
同理可以计算出 y 坐标对应的像素值。


应该是这样对吧

**Comment by Laomai-codefee** [comment]
1.0 的版本是经过了转换
pdfjs 的坐标圆点 在左下
konva 的坐标圆点 在左上
像这样转换就行了
