### ISSUE TITLE
调试出错，请问大佬的nodejs版本是多少？

### ISSUE THREAD

**Issue by mayamoon** [Laomai-codefee/pdfjs-annotation-extension#21]
我用18.12.1 以及 20.12.0 版本都无法调试代码报错
[webpack-cli] Failed to load 'D:\node_project\pdfjs-annotation-extension\configuration\[webpack.dev](http://webpack.dev/).config.js' config
[webpack-cli] Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- D:\node_project\pdfjs-annotation-extension\node_modules\ajv-keywords\dist\definitions\typeof.js
- D:\node_project\pdfjs-annotation-extension\node_modules\ajv-keywords\dist\keywords\typeof.js
- D:\node_project\pdfjs-annotation-extension\node_modules\ajv-keywords\dist\keywords\index.js
- D:\node_project\pdfjs-annotation-extension\node_modules\ajv-keywords\dist\index.js 
- D:\node_project\pdfjs-annotation-extension\node_modules\schema-utils\dist\validate.js
- D:\node_project\pdfjs-annotation-extension\node_modules\schema-utils\dist\index.js 
- D:\node_project\pdfjs-annotation-extension\node_modules\image-minimizer-webpack-plugin\dist\index.js
- D:\node_project\pdfjs-annotation-extension\webpack.config.js
- D:\node_project\pdfjs-annotation-extension\configuration\[webpack.dev](http://webpack.dev/).config.js     
- D:\node_project\pdfjs-annotation-extension\node_modules\webpack-cli\lib\webpack-cli.js
- D:\node_project\pdfjs-annotation-extension\node_modules\webpack-cli\lib\bootstrap.js
- D:\node_project\pdfjs-annotation-extension\node_modules\webpack-cli\bin\cli.js     
- D:\node_project\pdfjs-annotation-extension\node_modules\webpack\bin\webpack.js     
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\node_project\pdfjs-annotation-extension\node_modules\ajv-keywords\dist\definitions\typeof.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\ajv-keywords\\dist\\definitions\\typeof.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\ajv-keywords\\dist\\keywords\\typeof.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\ajv-keywords\\dist\\keywords\\index.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\ajv-keywords\\dist\\index.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\schema-utils\\dist\\validate.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\schema-utils\\dist\\index.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\image-minimizer-webpack-plugin\\dist\\index.js',
    'D:\\node_project\\pdfjs-annotation-extension\\webpack.config.js',
    'D:\\node_project\\pdfjs-annotation-extension\\configuration\\[webpack.dev](http://webpack.dev/).config.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\webpack-cli\\bin\\cli.js',
    'D:\\node_project\\pdfjs-annotation-extension\\node_modules\\webpack\\bin\\webpack.js'
  ]
}

**Comment by mayamoon** [comment]
通过强制设置ajv版本可以解决
  "ajv": "^7.0.0",
  "ajv-keywords": "^5.0.0"

**Comment by Laomai-codefee** [comment]
解决了就好～
