### ISSUE TITLE
关于如何使用

### ISSUE THREAD

**Issue by kenxt** [Laomai-codefee/pdfjs-annotation-extension#5]
下载了源码示例，传到web服务器上发现无法打开pdf文档，打开方式是：viewer.html?file=https://pdfpath
而通过pdf.js包中viewer.html就可以直接打开，不知道是什么原因

**Comment by Laomai-codefee** [comment]
请再描述得更具体些，无法打开，浏览器报了什么错

**Comment by kenxt** [comment]
看了一下有三个错误：
![pdferror](https://github.com/user-attachments/assets/1bb97664-ea17-413e-8492-0c98b80bc93c)

**Comment by kenxt** [comment]
问题解决了，在windows上重新生成了一遍：
git clone https://github.com/Laomai-codefee/pdfjs-annotation-extension.git
cd pdfjs-annotation-extension
npm install
npm run stats （npm run dev 生成后没测试）
example在nginx下可以运行了 
![pdfannotation](https://github.com/user-attachments/assets/85570af2-e403-4fb1-a268-c3fc8e33b50f)

**Comment by Laomai-codefee** [comment]
好，解决了就好。
