### ISSUE TITLE
请问大佬能否在此基础上实现文字编辑，可行性讨论

### ISSUE THREAD

**Issue by 948764321** [Laomai-codefee/pdfjs-annotation-extension#6]
目前批注是新增了 `canvas` 图层，我的想法是能否在此图层上继续完成文字编辑

现在有几个未知的难点
1. 可编辑文字范围，pdfjs 分割的太细了，这里用 ocr 处理吗？
2. 文字在批注图层编辑，如何和 pdfjs 图层结合？
3. 文件保存下载纯前端实现不了的话，后端结合 pdfBox 应该也能解决吧

我想在此基础上完成文字编辑，想向大佬请教一下，是否有解决不了的难点~谢谢

**Comment by Laomai-codefee** [comment]
你这里说的文字编辑，是指插入文字批注，还是编辑原有 pdf 的文字

如果是插入的文字编辑那可行，如果是编辑原有 pdf 文字基本上不可行

pdfjs 的是实现是 canvas 绘图，textlayer 仅做选择用途。
字体样式完全靠 canvas 绘制，textlayer 仅是占位符而已。
想依赖 canvas 层来做文字编辑，就是做一个类似 google doc 这样的编辑器，有点不太现实，难度太大。

**Comment by 948764321** [comment]
是文字编辑，我看腾讯文档就是基于 pdfjs 实现的。修改了原 pdfjs 的 canvas 图层，但我不知道怎么实现的

找了好久也没找到 web 端的支持 pdf 编辑的库，这个有推荐吗？

**Comment by Laomai-codefee** [comment]
我刚刚看了腾讯云文档，还确实是pdfjs 做到的，我把 canvas 删掉是这么个效果。
那应该是编辑文字层的时候，canvas 重新渲染了。
他能做到，我们可能就能做到，具体怎么做的，我要去研究下才懂
![iShot_2024-10-12_13 44 02](https://github.com/user-attachments/assets/139952f3-56ad-4990-8fbf-a5bf6eef69c9)

**Comment by 948764321** [comment]
谢谢大佬解答！
