### ISSUE TITLE
v2.0 保存功能点击无反应

### ISSUE THREAD

**Issue by 948764321** [Laomai-codefee/pdfjs-annotation-extension#7]
应该为保存下载文件吧， 现在看起来点击无反应

**Comment by Laomai-codefee** [comment]
保存需要配置保存地址，目前已经不支持下载了，因为批注插入不到文件中。
只能将批注数据提交到服务器

 ae_username= 批注人姓名，添加批注时显示的批注人姓名
  ae_get_url= 批注数据地址，通过此地址加载已保存的批注数据 示例 ./examples/pdfjs-4.3.136-dist/pdfjs-annotation-extension-testdata.json
  ae_post_url= 批注数据提交地址

**Comment by 948764321** [comment]
后续还要开放服务端代码吗？

**Comment by 948764321** [comment]
感谢作者！

**Comment by 948764321** [comment]
已解决
